version: '3'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - ~/postgresql_data:/var/lib/postgresql/data
    env_file:
      - ../.env